### ISSUE TITLE
Add Post Backend

### ISSUE THREAD

**Issue by codeforcent** [HSGamer/ImageExp-IssueTracker#2]
**Describe the bug**
Bug in form of Add Post Backend 

**To Reproduce**
//Steps to reproduce the behavior:
//1. Go to '...'
//2. Click on '....'
//3. Scroll down to '....'
//4. See error

**Expected behavior**
PicID should be auto increase and be replaced by img in base 64

**Screenshots**
https://user-images.githubusercontent.com/71592679/122240807-3f079f80-ceec-11eb-9558-f13dd7150518.png

**Desktop (please complete the following information):**
 //- OS: [e.g. iOS]
 //- Browser [e.g. chrome, safari]
// - Version [e.g. 22]

**Smartphone (please complete the following information):**
// - Device: [e.g. iPhone6]
 //- OS: [e.g. iOS8.1]
 //- Browser [e.g. stock browser, safari]
// - Version [e.g. 22]

**Additional context**
//Add any other context about the problem here.

**Comment by HSGamer** [comment]
It's intended. You can get the image in base64 with `/getpicturebyid`
