### ISSUE TITLE
Add post in Backend

### ISSUE THREAD

**Issue by codeforcent** [HSGamer/ImageExp-IssueTracker#3]
**Describe the bug**
Add attributes in Backend

**To Reproduce**
//Steps to reproduce the behavior:
//1. Go to '...'
//2. Click on '....'
//3. Scroll down to '....'
//4. See error

**Expected behavior**
Title and Description attributes should be added to form

**Screenshots**
![image](https://user-images.githubusercontent.com/71592679/122241556-da007980-ceec-11eb-90f3-471c6db7dae8.png)

**Desktop (please complete the following information):**
 //- OS: [e.g. iOS]
 //- Browser [e.g. chrome, safari]
// - Version [e.g. 22]

**Smartphone (please complete the following information):**
// - Device: [e.g. iPhone6]
 //- OS: [e.g. iOS8.1]
// - Browser [e.g. stock browser, safari]
 //- Version [e.g. 22]

**Additional context**
//Add any other context about the problem here.

**Comment by HSGamer** [comment]
Added
