### ISSUE TITLE
Add Picture Backend

### ISSUE THREAD

**Issue by codeforcent** [HSGamer/ImageExp-IssueTracker#4]
**Describe the bug**
Backend cannot receive information in valid form

**To Reproduce**

**Expected behavior**
Backend should repsonse properly

**Screenshots**
![image](https://user-images.githubusercontent.com/71592679/122516011-6cf9fa80-d038-11eb-85ba-efda086e235e.png)
![image](https://user-images.githubusercontent.com/71592679/122516109-8bf88c80-d038-11eb-9786-b55a8429f1ab.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HSGamer** [comment]
Fixed
